const R = [
['Общие положения','1.1. Каждый игрок обязан соблюдать правила сервера. Незнание правил не освобождает от ответственности.\n\n1.2. Администрация может рассматривать ситуации, не описанные прямо в правилах, исходя из их смысла и обстоятельств.\nНаказание: определяется администрацией в зависимости от нарушения.\n\n1.3. Запрещено намеренно обходить правила или использовать их формулировки для получения преимущества.\nНаказание: бан от 3 до 30 дней.'],
['Читы и стороннее ПО','2.1. Запрещены читы, модификации и сторонние программы, дающие преимущество: KillAura, AimBot, TriggerBot, AutoClicker, Reach, Fly, Speed, NoFall, ESP, X-Ray, FreeCam, Scaffold, Baritone и аналогичные.\nНаказание: перманентный бан.\n\n2.2. Запрещены чит-клиенты: Wurst, LiquidBounce, Meteor, Impact, Aristois, Inertia, BleachHack и аналогичные.\nНаказание: перманентный бан.\n\n2.3. Запрещены макросы и скрипты для автоматизации игровых действий с целью получения преимущества.\nНаказание: бан на 30 дней.\n\n2.4. Запрещено обходить или намеренно препятствовать работе античита.\nНаказание: перманентный бан.'],
['Баги и дюпы','3.1. Запрещено использовать баги, ошибки плагинов и механик для получения преимущества.\nНаказание: бан от 7 до 30 дней + удаление выгоды.\n\n3.2. Запрещены любые способы дублирования предметов или валюты.\nНаказание: перманентный бан + удаление ресурсов.\n\n3.3. Запрещено распространять серьёзные баги для массовой эксплуатации.\nНаказание: бан на 14 дней.\n\n3.4. Обнаруженные баги необходимо сообщать администрации.'],
['Гриферство','4.1. Запрещено разрушать, изменять или повреждать чужие постройки, фермы и территории без разрешения владельца.\n\n4.2. Запрещены поджоги, залив водой/лавой, изменение ландшафта и другие способы порчи чужого имущества.\nНаказание: бан на 7 дней + восстановление ущерба.\n\n4.3. Массовое или повторное гриферство.\nНаказание: бан на 30 дней + восстановление ущерба.\n\n4.4. Запрещено входить на закрытые территории, если хозяин просит уйти.'],
['PvP и убийства','5.1. PvP разрешено только в Аду и Эндер мире.\n\n5.2. Запрещается атаковать игрока в обычном мире.\nНаказание: бан на 3 дня.\n\n5.3. При убийстве без согласия и потере ресурсов игрок может создать тикет. Убийца обязан вернуть предметы.\nНаказание: бан на 3 дня + возврат ресурсов.\n\n5.4. Уничтоженные или проданные ресурсы компенсируются равноценным имуществом.\nНаказание: бан на 7 дней + компенсация.\n\n5.5. Отказ выполнить требование администрации о возврате ресурсов.\nНаказание: дополнительный бан на 14 дней.'],
['Воровство','6.1. Запрещено брать чужие предметы и ресурсы без разрешения владельца, в том числе из сундуков, бочек, шалкеров и других хранилищ.\nНаказание: бан на 7 дней + возврат украденного.\n\n6.2. Продажа, уничтожение, выбрасывание или передача украденного не освобождает от компенсации.\nНаказание: бан на 14 дней + полная компенсация.\n\n6.3. Массовая или систематическая кража.\nНаказание: бан на 30 дней + полное возмещение ущерба.'],
['Чат и общение','7.1. Запрещены флуд, спам и массовая отправка одинаковых сообщений.\nНаказание: мут от 15 минут до 6 часов.\n\n7.2. Запрещены оскорбления, унижение, провокации и разжигание конфликтов.\nНаказание: мут от 30 минут до 6 часов.\n\n7.3. Запрещены угрозы игрокам и администрации.\nНаказание: мут до 24 часов или бан до 30 дней.\n\n7.4. Запрещено распространение личной информации без согласия.\nНаказание: бан от 30 дней до перманентного.\n\n7.5. Запрещена реклама сторонних серверов и проектов.\nНаказание: бан на 7 дней; массовая реклама — перманентный бан.'],
['Торговля и экономика','8.1. Запрещено намеренно обманывать игроков при внутриигровой торговле.\nНаказание: бан на 7 дней + возврат ресурсов.\n\n8.2. Если ресурсы уничтожены, проданы или переданы, нарушитель обязан предоставить равноценную компенсацию.\nНаказание: бан на 14 дней + компенсация.\n\n8.3. Запрещено получать валюту или предметы через баги и дюпы.\nНаказание: перманентный бан + удаление незаконно полученного.'],
['Мультиаккаунты и обход наказаний','9.1. Несколько аккаунтов разрешены, если они не используются для нарушения правил.\n\n9.2. Запрещено использовать дополнительные аккаунты для обхода бана, мута и ограничений.\nНаказание: бан всех участвующих аккаунтов + продление наказания.\n\n9.3. Запрещено передавать аккаунты для обхода наказаний.\nНаказание: бан на 30 дней.'],
['Тикеты и администрация','10.1. Жалоба должна содержать ник нарушителя, описание и по возможности доказательства: видео, скриншоты, время и координаты.\n\n10.2. Запрещено предоставлять администрации ложную информацию.\nНаказание: бан на 7 дней.\n\n10.3. Запрещено подделывать доказательства.\nНаказание: бан на 14 дней.\n\n10.4. Запрещено создавать ложные тикеты с целью навредить игроку.\nНаказание: бан на 7 дней.\n\n10.5. Игрок обязан выполнить законное требование администрации.\nНаказание за отказ: бан на 14 дней.'],
['Нагрузка на сервер','11.1. Запрещено намеренно создавать лаг-машины, чрезмерное число сущностей, предметов или механизмов для ухудшения работы сервера.\nНаказание: бан на 14 дней + удаление источника нагрузки.\n\n11.2. Повторное или массовое создание нагрузки.\nНаказание: бан на 30 дней.\n\n11.3. Намеренная попытка вывести сервер из строя.\nНаказание: перманентный бан.'],
['Повторные нарушения','12.1. При повторном нарушении администрация может увеличить срок наказания.\n\n12.2. Систематические нарушения могут привести к перманентной блокировке.\nНаказание: определяется по количеству и тяжести нарушений.\n\n12.3. Донат, привилегии или статус игрока не освобождают от наказания.\n\n12.4. Администрация может удалить незаконно полученные ресурсы и потребовать возмещение ущерба.']
];
const ruleMarkup = R.map(([title, text], i) => `<article class="rule accordion"><button class="accordion-trigger" aria-expanded="false"><span class="rule-number">${String(i + 1).padStart(2,'0')}</span><h3>${title}</h3><span class="chevron">›</span></button><div class="accordion-body"><div><p>${text}</p></div></div></article>`).join('');
const P = {
home:['Добро пожаловать','Твой мир. Твои правила.','Vanilla+ сервер для тех, кто любит настоящее выживание, уютные постройки и хорошую компанию.',`<div class="hero"><img class="server-avatar" src="proxima-avatar.png" alt="Аватар сервера PROXIMA"><h2>Настоящий <em>Minecraft</em>, каким он должен быть.</h2><p>PROXIMA — ванильное выживание с полезными механиками, активным сообществом и уважением к каждому игроку.</p></div><h2 class="section-title">Начни отсюда</h2><div class="cards"><button class="card action-card" data-go="rules"><div class="card-icon">⚑</div><h3>Правила сервера</h3><p>Узнай правила и играй спокойно.</p></button><button class="card action-card" data-go="guides"><div class="card-icon">▤</div><h3>Полезные гайды</h3><p>Всё о модах и экономике сервера.</p></button><button class="card action-card" data-go="play"><div class="card-icon">▶</div><h3>Подключиться</h3><p>Три шага до игры на PROXIMA.</p></button></div>`],
plugins:['Серверные механики','Кастомные плагины','Улучшения, которые сохраняют ванильную атмосферу и делают игру удобнее.',`<div class="feature-grid"><article class="feature"><span class="tag">ПОРТАЛЫ</span><h3>Любой размер портала</h3><p>Создавайте порталы любого размера: 1×2, 2×2, 3×3, 3×2 и больше.</p></article><article class="feature"><span class="tag">PROXIMA+</span><h3>Размер персонажа</h3><p>С Proxima+ и выше доступна панель <b>/proxima</b>: размер 0.8, 1.0 (стандарт) или 1.2.</p></article></div>`],
mods:['Клиентские дополнения','Моды','Сервер работает без обязательных модов. Установите только то, что делает игру комфортнее.',`<div class="cards"><article class="card"><div class="card-icon">◈</div><h3>Клиентские моды</h3><p>Полезные моды и инструкция по их установке доступны в разделе «Гайды».</p></article></div>`],
rules:['Общее пространство','Правила сервера','Нажмите на нужный раздел, чтобы прочитать правила полностью.',`<div class="rule-list">${ruleMarkup}</div>`],
ranks:['Поддержка проекта','Привилегии','Поддержите PROXIMA и получите больше удобных возможностей для игры.',`<div class="rank-grid"><article class="rank"><span class="tag">БЕСПЛАТНО</span><h3>Игрок</h3><p>Полный доступ к выживанию, чату и всем базовым механикам сервера.</p><div class="price">Бесплатно</div></article><article class="rank"><span class="tag">PROXIMA+</span><h3>Proxima+</h3><p>9 точек дома<br>12 слотов на аукционе<br>Панель /proxima — изменение размера<br>Поддержка сервера</p><div class="price">120 ₽</div><button class="buy-button" data-product="plus" data-name="Proxima+" data-price="120">В корзину</button></article><article class="rank"><span class="tag">PROXIMA++</span><h3>Proxima++</h3><p>27 точек дома<br>18 слотов на аукционе<br>Панель /proxima<br>Вход на полный сервер без очереди<br>Поддержка сервера</p><div class="price">320 ₽</div><button class="buy-button" data-product="plusplus" data-name="Proxima++" data-price="320">В корзину</button></article><article class="rank"><span class="tag">PROXIMA+++</span><h3>Proxima+++</h3><p>90 точек дома<br>30 слотов на аукционе<br>Панель /proxima<br>Вход на полный сервер без очереди<br>Поддержка сервера</p><div class="price">850 ₽</div><button class="buy-button" data-product="plusplusplus" data-name="Proxima+++" data-price="850">В корзину</button></article></div>`],
meteors:['Донат-валюта','Метеоры','Выберите пакет метеоров для покупки. Одновременно в корзине может быть только один товар.',`<div class="rank-grid"><article class="rank"><span class="tag">МЕТЕОРЫ</span><h3>400 метеоров</h3><p>Донат-валюта сервера PROXIMA.</p><div class="price">85 ₽</div><button class="buy-button" data-product="meteors-400" data-name="400 метеоров" data-price="85">В корзину</button></article><article class="rank"><span class="tag">МЕТЕОРЫ</span><h3>2 500 метеоров</h3><p>Донат-валюта сервера PROXIMA.</p><div class="price">430 ₽</div><button class="buy-button" data-product="meteors-2500" data-name="2 500 метеоров" data-price="430">В корзину</button></article><article class="rank"><span class="tag">МЕТЕОРЫ</span><h3>5 500 метеоров</h3><p>Донат-валюта сервера PROXIMA.</p><div class="price">860 ₽</div><button class="buy-button" data-product="meteors-5500" data-name="5 500 метеоров" data-price="860">В корзину</button></article><article class="rank"><span class="tag">МЕТЕОРЫ</span><h3>32 000 метеоров</h3><p>Донат-валюта сервера PROXIMA.</p><div class="price">4 300 ₽</div><button class="buy-button" data-product="meteors-32000" data-name="32 000 метеоров" data-price="4300">В корзину</button></article><article class="rank"><span class="tag">МЕТЕОРЫ</span><h3>70 000 метеоров</h3><p>Донат-валюта сервера PROXIMA.</p><div class="price">8 600 ₽</div><button class="buy-button" data-product="meteors-70000" data-name="70 000 метеоров" data-price="8600">В корзину</button></article></div>`],
cart:['Магазин PROXIMA','Корзина','В корзину можно добавить только одну привилегию или пакет метеоров.',``],
guides:['База знаний','Гайды','Две главные инструкции, которые пригодятся игроку PROXIMA.',`<div class="guide-list"><article class="guide"><span class="guide-number">01</span><div><h3>Экономика и торговля</h3><p>Как пользоваться аукционом, торговать с игроками и распоряжаться валютой.</p></div><span class="guide-arrow">→</span></article><article class="guide"><span class="guide-number">02</span><div><h3>Как установить моды</h3><p>Установите загрузчик модов, скачайте мод подходящей версии и перенесите его в папку mods.</p></div><span class="guide-arrow">→</span></article></div>`],
play:['Время приключений','Как начать играть?','Пройдите заявку в Discord — после одобрения можно подключаться к серверу.',`<div class="steps"><article class="step"><h3>Установите Minecraft</h3><p>Вам необходима версия Minecraft Java Edition 1.21.11.</p></article><article class="step"><h3>Подайте заявку</h3><p>Зайдите в наш Discord-сервер и подайте заявку на проходку.</p></article><article class="step"><h3>Подключайтесь</h3><p>После одобрения заявки заходите на сервер и играйте с комфортом!</p></article></div><div class="play-box"><p>IP сервера: <strong>proxima.play.ski</strong></p><div><a class="copy-button" href="https://discord.gg/ezuxYByHgd" target="_blank" rel="noopener">Открыть Discord</a> <button class="copy-button" id="copyIp">Скопировать IP</button></div></div>`]
};
const content=document.querySelector('#content'), items=[...document.querySelectorAll('.nav-item')];
let cart=JSON.parse(localStorage.proximaCart||'null');
function updateCartCount(){const count=document.querySelector('#cartCount');count.textContent=cart?'1':'0';count.classList.toggle('visible',!!cart)}
function showToast(message){let toast=document.querySelector('.toast');if(!toast){toast=document.createElement('div');toast.className='toast';document.body.append(toast)}toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function cartMarkup(){return cart?`<article class="cart-product"><span class="tag">ВЫБРАННЫЙ ТОВАР</span><h2>${cart.name}</h2><p>Введите свой Minecraft-ник — он будет передан вместе с заказом.</p><input class="nickname-input" id="nickname" maxlength="16" autocomplete="off" placeholder="Minecraft-ник" aria-label="Minecraft-ник"><div class="checkout-bar"><strong class="price">${cart.price} ₽</strong><div><button class="remove-button" id="removeCart">Убрать</button> <button class="buy-button" id="checkout">Перейти к оплате</button></div></div></article>`:`<div class="cart-empty">Корзина пуста. Выберите одну из привилегий или пакет метеоров.</div>`}
function go(id){items.forEach(x=>x.classList.toggle('active',x.dataset.page===id));render(id);history.replaceState(null,'',`#${id}`)}
function render(id){const p=P[id]||P.home;content.innerHTML=`<header class="page-head"><div><span class="eyebrow">${p[0]}</span><h1>${p[1]}</h1><p>${p[2]}</p></div><div class="server-ip">СЕРВЕР ОНЛАЙН<b>proxima.play.ski</b></div></header>${id==='cart'?cartMarkup():p[3]}`;content.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));content.querySelectorAll('.buy-button[data-product]').forEach(x=>x.onclick=()=>{if(cart){showToast('Вы не можете положить в корзину больше 1 товара!');return}cart={id:x.dataset.product,name:x.dataset.name,price:x.dataset.price};localStorage.proximaCart=JSON.stringify(cart);updateCartCount();showToast('Товар добавлен в корзину');});content.querySelectorAll('.accordion-trigger').forEach(x=>x.onclick=()=>{const a=x.closest('.accordion'),v=a.classList.toggle('open');x.setAttribute('aria-expanded',v)});const remove=document.querySelector('#removeCart');if(remove)remove.onclick=()=>{cart=null;localStorage.removeItem('proximaCart');updateCartCount();render('cart')};const checkout=document.querySelector('#checkout');if(checkout)checkout.onclick=async()=>{const nickname=document.querySelector('#nickname').value.trim();checkout.disabled=true;checkout.textContent='Создаём счёт…';try{const response=await fetch('/api/create-invoice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:cart.id,nickname})});const data=await response.json();if(!response.ok)throw new Error(data.error);location.href=data.paymentUrl}catch(error){showToast(error.message||'Не удалось создать счёт.');checkout.disabled=false;checkout.textContent='Перейти к оплате'}};const c=document.querySelector('#copyIp');if(c)c.onclick=async()=>{await navigator.clipboard.writeText('proxima.play.ski');c.textContent='Скопировано ✓';setTimeout(()=>c.textContent='Скопировать IP',1700)}}
items.forEach(x=>x.onclick=()=>go(x.dataset.page));document.querySelector('.brand').onclick=e=>{e.preventDefault();go('home')};const t=document.querySelector('#themeToggle');if(localStorage.theme==='light')document.body.classList.add('light');t.onclick=()=>{document.body.classList.toggle('light');localStorage.theme=document.body.classList.contains('light')?'light':'dark'};document.onpointermove=e=>{document.body.style.setProperty('--mouse-x',e.clientX+'px');document.body.style.setProperty('--mouse-y',e.clientY+'px')};async function refreshOnline(){try{const s=await fetch('/api/server-status').then(r=>r.json());document.querySelector('#onlineCount').textContent=s.online?s.players:'—';document.querySelector('#onlineDot').style.opacity=s.online?'1':'.35'}catch{document.querySelector('#onlineCount').textContent='—'}}updateCartCount();refreshOnline();setInterval(refreshOnline,30000);go(P[location.hash.slice(1)]?location.hash.slice(1):'home');
